/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIdSetupRouteImport } from './routes/quiz/$id/setup'
import { Route as QuizIdResultsRouteImport } from './routes/quiz/$id/results'
import { Route as QuizIdPlayRouteImport } from './routes/quiz/$id/play'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdSetupRoute = QuizIdSetupRouteImport.update({
  id: '/quiz/$id/setup',
  path: '/quiz/$id/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdResultsRoute = QuizIdResultsRouteImport.update({
  id: '/quiz/$id/results',
  path: '/quiz/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdPlayRoute = QuizIdPlayRouteImport.update({
  id: '/quiz/$id/play',
  path: '/quiz/$id/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/quiz/$id/play': typeof QuizIdPlayRoute
  '/quiz/$id/results': typeof QuizIdResultsRoute
  '/quiz/$id/setup': typeof QuizIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/quiz/$id/play': typeof QuizIdPlayRoute
  '/quiz/$id/results': typeof QuizIdResultsRoute
  '/quiz/$id/setup': typeof QuizIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/quiz/$id/play': typeof QuizIdPlayRoute
  '/quiz/$id/results': typeof QuizIdResultsRoute
  '/quiz/$id/setup': typeof QuizIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scores'
    | '/settings'
    | '/quiz/$id/play'
    | '/quiz/$id/results'
    | '/quiz/$id/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scores'
    | '/settings'
    | '/quiz/$id/play'
    | '/quiz/$id/results'
    | '/quiz/$id/setup'
  id:
    | '__root__'
    | '/'
    | '/scores'
    | '/settings'
    | '/quiz/$id/play'
    | '/quiz/$id/results'
    | '/quiz/$id/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScoresRoute: typeof ScoresRoute
  SettingsRoute: typeof SettingsRoute
  QuizIdPlayRoute: typeof QuizIdPlayRoute
  QuizIdResultsRoute: typeof QuizIdResultsRoute
  QuizIdSetupRoute: typeof QuizIdSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id/setup': {
      id: '/quiz/$id/setup'
      path: '/quiz/$id/setup'
      fullPath: '/quiz/$id/setup'
      preLoaderRoute: typeof QuizIdSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id/results': {
      id: '/quiz/$id/results'
      path: '/quiz/$id/results'
      fullPath: '/quiz/$id/results'
      preLoaderRoute: typeof QuizIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id/play': {
      id: '/quiz/$id/play'
      path: '/quiz/$id/play'
      fullPath: '/quiz/$id/play'
      preLoaderRoute: typeof QuizIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScoresRoute: ScoresRoute,
  SettingsRoute: SettingsRoute,
  QuizIdPlayRoute: QuizIdPlayRoute,
  QuizIdResultsRoute: QuizIdResultsRoute,
  QuizIdSetupRoute: QuizIdSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
